/**
 * @file DigitalRecords.hpp
 * @brief Defines digital test record structures used in Keysight i3070 ICT system
 * 
 * This header contains all digital test record structures including digital tests,
 * device pin lists, PLD programming results, and ConnectCheck tests. These records
 * are generated by various digital test statements and provide detailed information
 * about digital component testing results.
 * 
 * @author Keysight Log Parser Team
 * @version 1.0
 * @date 2025-06-19
 */

#pragma once

#include "../core/LogRecord.hpp"
#include "../enums/TestStatus.hpp"
#include "../enums/LogRecordPrefix.hpp"
#include <string>
#include <vector>
#include <optional>
#include <nlohmann/json.hpp>

namespace i3070::records {

/**
 * @struct DigitalTestRecord
 * @brief Record structure for digital test results (@D-T)
 */
struct DigitalTestRecord : public core::LogRecord {
    enums::DigitalTestStatus test_status;       ///< Test execution status
    int test_substatus;                         ///< 6-bit binary substatus flags
    std::optional<int> failing_vector_number;  ///< Vector number that failed (0 if passed)
    int pin_count;                             ///< Number of pins that failed
    std::string test_designator;               ///< Test identifier/name
    
    DigitalTestRecord() : LogRecord(enums::LogRecordPrefix::D_T),
                         test_status(enums::DigitalTestStatus::PASSED),
                         test_substatus(0),
                         failing_vector_number(0),
                         pin_count(0) {}
    
    std::vector<enums::DigitalTestSubstatus> getSubstatusFlags() const;
    void setSubstatusFlags(const std::vector<enums::DigitalTestSubstatus>& flags);
    
    bool isPassed() const {
        return test_status == enums::DigitalTestStatus::PASSED;
    }
    bool isFailed() const {
        return test_status == enums::DigitalTestStatus::FAILED;
    }
    bool isFatalError() const {
        return test_status == enums::DigitalTestStatus::FATAL_ERROR;
    }

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct DevicePinRecord
 * @brief Record structure for device pin list (@DPIN)
 */
struct DevicePinRecord : public core::LogRecord {
    std::string device_name;
    // Uses vector<variant<string, vector<string>>> logic in cpp but stored as node_pin_list
    // The cpp uses `json node_pin_list` implicitly? No, `vector<variant...>` is complex.
    // Let's check cpp: `j[JSON_KEY_NODE_PIN_LIST] = node_pin_list;`
    // And `node_pin_list` is pushed back with strings or vector<string>.
    // So it must be a `nlohmann::json` object or a variant.
    // In `DevicePinRecord::fromFields`, `node_pin_list` seems to be a member.
    // If it holds mixed types, it might be `nlohmann::json` or a custom variant.
    // Let's assume it's `nlohmann::json` or `std::vector<nlohmann::json>` based on usage.
    // Wait, `addNodePin` takes string.
    // The cpp `node_pin_list.push_back(arr)` suggests it supports vector push back.
    // If it's `nlohmann::json`, `push_back` works for array.
    nlohmann::json node_pin_list = nlohmann::json::array(); 
    
    // thru_devnode_list is optional vector<string>?
    // `thru_devnode_list->push_back(node_id)`
    std::optional<std::vector<std::string>> thru_devnode_list;

    DevicePinRecord() : LogRecord(enums::LogRecordPrefix::DPIN) {}

    void fromFields(const std::vector<std::string>& fields) override;
    void addNodePin(const std::string& node_id, const std::string& device_pin);
    void addDriveThruPair(const std::string& node_id, const std::string& device_id);
    nlohmann::json toJson() const override;
};

/**
 * @struct PLDProgrammingRecord
 * @brief Record structure for PLD programming results (@D-PLD)
 */
struct PLDProgrammingRecord : public core::LogRecord {
    std::string filename;
    std::string action;
    int action_return_code;
    std::string result_message;
    int player_program_counter;

    PLDProgrammingRecord() : LogRecord(enums::LogRecordPrefix::D_PLD), action_return_code(0), player_program_counter(0) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct ExportRecord
 * @brief Record structure for export (@EXPORT? No, prefix unknown, maybe handled via factory default or not used)
 * Wait, cpp has `ExportRecord`. Prefix? `toJson` uses `rec.prefix`.
 * Factory does not instantiate `ExportRecord`.
 * But I should define it if it's in cpp.
 */
struct ExportRecord : public core::LogRecord {
    std::string key;
    std::string field;

    ExportRecord() : LogRecord(enums::LogRecordPrefix::UNKNOWN) {} // Prefix?

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct NoteRecord
 * @brief Record structure for notes (@NOTE? Factory doesn't have it)
 */
struct NoteRecord : public core::LogRecord {
    std::string note_name;
    std::string note_string;

    NoteRecord() : LogRecord(enums::LogRecordPrefix::UNKNOWN) {} 

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct ConnectCheckRecord
 * @brief Record structure for connect check (@CCHK)
 */
struct ConnectCheckRecord : public core::LogRecord {
    enums::GenericTestStatus test_status;
    int pin_count;
    std::string device_designator;

    ConnectCheckRecord() : LogRecord(enums::LogRecordPrefix::CCHK), test_status(enums::GenericTestStatus::PASS), pin_count(0) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override; // Note: cpp uses free function `toJson(const ...)` but virtual override should work if implemented as member
};

/**
 * @struct PolarityCheckRecord
 * @brief Record structure for polarity check (@PCHK)
 */
struct PolarityCheckRecord : public core::LogRecord {
    enums::GenericTestStatus test_status;
    std::string test_designator;

    PolarityCheckRecord() : LogRecord(enums::LogRecordPrefix::PCHK), test_status(enums::GenericTestStatus::PASS) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct TestJetRecord
 * @brief Record structure for TestJet (@TJET)
 */
struct TestJetRecord : public core::LogRecord {
    enums::GenericTestStatus test_status;
    int pin_count;
    std::string test_designator;

    TestJetRecord() : LogRecord(enums::LogRecordPrefix::TJET), test_status(enums::GenericTestStatus::PASS), pin_count(0) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct IndictmentRecord
 * @brief Record structure for indictment (@INDICT)
 */
struct IndictmentRecord : public core::LogRecord {
    std::string technique;
    std::vector<std::string> device_list;
    std::optional<double> est_resistance;
    std::optional<double> est_capacitance;
    std::optional<double> est_inductance;
    std::string est_model;

    IndictmentRecord() : LogRecord(enums::LogRecordPrefix::INDICT) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct PinRecord
 * @brief Record structure for pin info (@PIN)
 */
struct PinRecord : public core::LogRecord {
    std::optional<int> pin_count;
    std::vector<std::string> pins;

    PinRecord() : LogRecord(enums::LogRecordPrefix::PIN) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

} // namespace i3070::records
