/**
 * @file ShortRecords.hpp
 * @brief Defines shorts and opens test record structures for Keysight i3070 ICT system
 * 
 * This header contains all structures related to shorts testing and its subrecords,
 * including the main shorts record (@TS) and nested subrecords (@TS_S, @TS_D, @TS_O, @TS_P).
 * These records describe shorts, opens, and phantom conditions encountered during test shorts.
 * 
 * Generated by: test shorts statement
 * 
 * @version 1.0
 * @date 2025-06-19
 */

#pragma once

#include "../core/LogRecord.hpp"
#include "../enums/LogRecordPrefix.hpp"
#include "../enums/TestStatus.hpp"
#include <string>
#include <vector>
#include <optional>
#include <nlohmann/json.hpp>

namespace i3070::records {

/**
 * @struct ShortsTestRecord
 * @brief Main shorts test record (@TS)
 */
struct ShortsTestRecord : public core::LogRecord {
    enums::GenericTestStatus test_status;  ///< Overall shorts test status[1]
    int shorts_count;                      ///< Count of unexpected shorted nodes[2]
    int opens_count;                       ///< Count of unexpected open nodes[2]
    int phantoms_count;                    ///< Count of phantom shorts[2]
    std::string designator;                ///< Optional designator string[2]

    ShortsTestRecord()
      : LogRecord(enums::LogRecordPrefix::TS),
        test_status(enums::GenericTestStatus::PASS),
        shorts_count(0),
        opens_count(0),
        phantoms_count(0),
        designator("") {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct TsSourceRecord
 * @brief Record for shorts test source information (@TS_S)
 */
struct TsSourceRecord : public core::LogRecord {
    int shorts_count;               ///< Number of shorted destinations[2]
    int phantoms_count;             ///< Number of phantom shorts[2]
    std::string source_node;        ///< Source node identifier[2]

    TsSourceRecord()
      : LogRecord(enums::LogRecordPrefix::TS_S),
        shorts_count(0),
        phantoms_count(0) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct TsDestinationRecord
 * @brief Record for destination nodes shorted to a source (@TS_D)
 */
struct TsDestinationRecord : public core::LogRecord {
    // Matching .cpp implementation: vector of pair<string, double>
    std::vector<std::pair<std::string, double>> destination_list;

    TsDestinationRecord() : LogRecord(enums::LogRecordPrefix::TS_D) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct TsOpenRecord
 * @brief Record for opens test result (@TS_O)
 */
struct TsOpenRecord : public core::LogRecord {
    std::string source_node;
    std::string destination_node;
    std::optional<double> deviation;

    TsOpenRecord() : LogRecord(enums::LogRecordPrefix::TS_O) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct TsPhantomRecord
 * @brief Record for phantom shorts (@TS_P)
 */
struct TsPhantomRecord : public core::LogRecord {
    std::optional<double> deviation;

    TsPhantomRecord() : LogRecord(enums::LogRecordPrefix::TS_P) {}

    void fromFields(const std::vector<std::string>& fields) override;
    nlohmann::json toJson() const override;
};

} // namespace i3070::records
