/**
 * @file DigitalRecords.hpp
 * @brief Defines digital test record structures used in Keysight i3070 ICT system
 * 
 * This header contains all digital test record structures including digital tests,
 * device pin lists, PLD programming results, and ConnectCheck tests. These records
 * are generated by various digital test statements and provide detailed information
 * about digital component testing results.
 * 
 * @author Keysight Log Parser Team
 * @version 1.0
 * @date 2025-06-19
 */

#ifndef KEYSIGHT_LOG_RECORDS_DIGITALRECORDS_HPP
#define KEYSIGHT_LOG_RECORDS_DIGITALRECORDS_HPP

#include "../core/LogRecord.hpp"
#include "../enums/TestStatus.hpp"
#include "../enums/LogRecordPrefix.hpp"
#include "../enums/FieldType.hpp"
#include "../utils/JsonKeys.hpp"
#include "../utils/SafeConversion.hpp"
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include <iostream>
#include <nlohmann/json.hpp>

using namespace std;
using json = nlohmann::json;

namespace keysight_log {
namespace records {

/**
 * @struct DigitalTestRecord
 * @brief Record structure for digital test results (@D-T)
 * 
 * This record describes the results of a digital test performed by the test statement.
 * It contains test status, substatus flags, vector information, and pin counts.
 * When pin logging is enabled, it is followed by @DPIN subrecords.
 * 
 * Generated by: test statement
 * Subrecords: @DPIN (when logging pins to list failing device pins)
 * 
 * Format: {@D-T|test status|test substatus|failing vector number|pin count|test designator}
 */
struct DigitalTestRecord : public core::LogRecord {
    enums::DigitalTestStatus test_status;       ///< Test execution status
    int test_substatus;                         ///< 6-bit binary substatus flags
    optional<int> failing_vector_number;  ///< Vector number that failed (0 if passed)
    int pin_count;                             ///< Number of pins that failed
    string test_designator;               ///< Test identifier/name
    
    /**
     * @brief Default constructor
     */
    DigitalTestRecord() : LogRecord(enums::LogRecordPrefix::D_T),
                         test_status(enums::DigitalTestStatus::PASSED),
                         test_substatus(0),
                         failing_vector_number(0),
                         pin_count(0) {}
    
    /**
     * @brief Gets decoded substatus flags
     * @return Vector of DigitalTestSubstatus flags that are set
     */
    vector<enums::DigitalTestSubstatus> getSubstatusFlags() const;
    
    /**
     * @brief Sets substatus from individual flags
     * @param flags Vector of DigitalTestSubstatus flags to set
     */
    void setSubstatusFlags(const vector<enums::DigitalTestSubstatus>& flags);
    
    /**
     * @brief Checks if test passed
     * @return true if test status indicates success
     */
    bool isPassed() const {
        return test_status == enums::DigitalTestStatus::PASSED;
    }
    
    /**
     * @brief Checks if test failed
     * @return true if test status indicates failure
     */
    bool isFailed() const {
        return test_status == enums::DigitalTestStatus::FAILED;
    }
    
    /**
     * @brief Checks if fatal error occurred
     * @return true if test encountered fatal error
     */
    bool isFatalError() const {
        return test_status == enums::DigitalTestStatus::FATAL_ERROR;
    }

    void fromFields(const vector<string>& fields) override;
    json toJson() const override;
};

/**
 * @struct DevicePinRecord
 * @brief Record structure for device pin lists (@DPIN)
 * 
 * This record contains a list of device pins for a single device, including
 * node-pin pairs and optional DriveThru device information. It appears as
 * a subrecord of digital tests and probe records.
 * 
 * Generated by: test statement, probe statement, probe failures statement
 * 
 * Format: {@DPIN|device name|node pin list} or 
 *         {@DPIN|device name|node pin list|thru devnode list} (with DriveThru)
 */
struct DevicePinRecord : public core::LogRecord {
    string device_name;                   ///< Device name or test designator
    std::vector<nlohmann::json> node_pin_list; ///< Node/pin list: can be string or array
    optional<vector<string>> thru_devnode_list;  ///< DriveThru device-node pairs
    
    /**
     * @brief Default constructor
     */
    DevicePinRecord() : LogRecord(enums::LogRecordPrefix::DPIN) {}
    
    /**
     * @brief Constructor with device name
     * @param name Device name or designator
     */
    explicit DevicePinRecord(const std::string& name) 
        : LogRecord(enums::LogRecordPrefix::DPIN), device_name(name) {}
    
    /**
     * @brief Gets the number of device pins
     * @return Number of pins (half the size of node_pin_list)
     */
    int getPinCount() const {
        return static_cast<int>(node_pin_list.size()) / 2;
    }
    
    /**
     * @brief Adds a node-pin pair to the list
     * @param node_id Node identifier string
     * @param device_pin Device pin identifier
     */
    void addNodePin(const string& node_id, const string& device_pin);
    
    /**
     * @brief Adds a DriveThru device-node pair
     * @param node_id Node identifier string  
     * @param device_id Device identifier string
     */
    void addDriveThruPair(const string& node_id, const string& device_id);
    
    /**
     * @brief Checks if record has DriveThru information
     * @return true if DriveThru data is present
     */
    bool hasDriveThru() const {
        return thru_devnode_list.has_value() && !thru_devnode_list->empty();
    }

    void fromFields(const vector<string>& fields) override;
    json toJson() const override;
};

/**
 * @struct PLDProgrammingRecord
 * @brief Record structure for PLD programming results (@D-PLD)
 * 
 * This record describes the results of PLD (Programmable Logic Device) programming
 * operations including success/failure status, action details, and error information.
 * May contain @EXPRT and @NOTE subrecords for additional data.
 * 
 * Generated by: play statement (PLD ISP operations)
 * Subrecords: @EXPRT (export data), @NOTE (programmer notes)
 * 
 * Format: {@D-PLD|filename|action|action return code|result message|player program counter}
 */
struct PLDProgrammingRecord : public core::LogRecord {
    string filename;                      ///< Compiled program file name
    string action;                        ///< STAPL source action performed
    int action_return_code;                    ///< Action execution return code (0=success)
    string result_message;                ///< Error condition description
    int player_program_counter;                ///< JBC opcode index where failure occurred
    
    /**
     * @brief Default constructor
     */
    PLDProgrammingRecord() : LogRecord(enums::LogRecordPrefix::D_PLD),
                            action_return_code(0),
                            player_program_counter(0) {}
    
    /**
     * @brief Constructor with filename
     * @param file Program file name
     */
    explicit PLDProgrammingRecord(const string& file)
        : LogRecord(enums::LogRecordPrefix::D_PLD),
          filename(file),
          action_return_code(0),
          player_program_counter(0) {}
    
    /**
     * @brief Checks if programming operation succeeded
     * @return true if return code indicates success
     */
    bool isSuccessful() const {
        return action_return_code == 0;
    }
    
    /**
     * @brief Checks if programming operation failed
     * @return true if return code indicates failure
     */
    bool isFailed() const {
        return action_return_code != 0;
    }
    
    /**
     * @brief Gets severity level of the result
     * @return 0 for success, 1 for failure
     */
    int getSeverity() const {
        return action_return_code == 0 ? 0 : 1;
    }

    void fromFields(const vector<string>& fields) override;
    json toJson() const override;
};

/**
 * @struct ExportRecord
 * @brief Subrecord structure for PLD export data (@EXPRT)
 * 
 * This subrecord appears within @D-PLD records and contains exported variable
 * data from STAPL programming operations. Generated by export commands in
 * the programming file.
 * 
 * Generated by: STAPL export commands
 * 
 * Format: {@EXPRT|key|field}
 */
struct ExportRecord : public core::LogRecord {
    string key;                           ///< Variable name identifier
    string field;                         ///< Variable value when exported
    
    /**
     * @brief Default constructor
     */
    ExportRecord() : LogRecord(enums::LogRecordPrefix::UNKNOWN) {}  // No specific prefix for EXPRT
    
    /**
     * @brief Constructor with key-value pair
     * @param variable_key Variable identifier
     * @param variable_value Variable value
     */
    ExportRecord(const string& variable_key, const string& variable_value)
        : LogRecord(enums::LogRecordPrefix::UNKNOWN), key(variable_key), field(variable_value) {}

    void fromFields(const vector<string>& fields) override;
    json toJson() const override;
};

/**
 * @struct NoteRecord
 * @brief Subrecord structure for PLD programming notes (@NOTE)
 * 
 * This subrecord appears within @D-PLD records and contains note information
 * from STAPL source files. Generated by note header commands within the
 * STAPL source file.
 * 
 * Generated by: Note header commands in STAPL source
 * 
 * Format: {@NOTE|note name|note string}
 */
struct NoteRecord : public core::LogRecord {
    string note_name;                     ///< Note field keyword name
    string note_string;                   ///< Note field contents
    
    /**
     * @brief Default constructor
     */
    NoteRecord() : LogRecord(enums::LogRecordPrefix::UNKNOWN) {}  // No specific prefix for NOTE
    
    /**
     * @brief Constructor with note data
     * @param name Note keyword identifier
     * @param content Note content string
     */
    NoteRecord(const string& name, const string& content)
        : LogRecord(enums::LogRecordPrefix::UNKNOWN), note_name(name), note_string(content) {}

    void fromFields(const vector<string>& fields) override;
    json toJson() const override;
};

/**
 * @struct ConnectCheckRecord
 * @brief Record structure for ConnectCheck test results (@CCHK)
 * 
 * This record describes the results of ConnectCheck tests on Mux systems.
 * ConnectCheck verifies proper connectivity and can identify connection
 * problems in the test setup.
 * 
 * Generated by: test statement (on Mux systems)
 * Subrecords: @DPIN (when logging pins to list failing device pins)
 * 
 * Format: {@CCHK|test status|pin count|test designator}
 */
struct ConnectCheckRecord : public core::LogRecord {
    enums::GenericTestStatus test_status;      ///< Test execution status
    int pin_count;                             ///< Number of failing pins
    std::string device_designator;             ///< Device identifier being tested
    
    /**
     * @brief Default constructor
     */
    ConnectCheckRecord() : LogRecord(enums::LogRecordPrefix::CCHK),
                          test_status(enums::GenericTestStatus::PASS),
                          pin_count(0) {}
    
    /**
     * @brief Constructor with device designator
     * @param designator Device identifier
     */
    explicit ConnectCheckRecord(const std::string& designator)
        : LogRecord(enums::LogRecordPrefix::CCHK),
          test_status(enums::GenericTestStatus::PASS),
          pin_count(0),
          device_designator(designator) {}
    
    /**
     * @brief Checks if test passed
     * @return true if test status indicates success
     */
    bool isPassed() const {
        return test_status == enums::GenericTestStatus::PASS;
    }
    
    /**
     * @brief Checks if test failed
     * @return true if test status indicates failure
     */
    bool isFailed() const {
        return test_status == enums::GenericTestStatus::FAIL;
    }
    
    /**
     * @brief Checks if fatal error occurred
     * @return true if test encountered fatal error
     */
    bool isFatalError() const {
        return test_status == enums::GenericTestStatus::FATAL_ERROR;
    }
    
    /**
     * @brief Gets the number of failing pins
     * @return Pin count (0 if test passed)
     */
    int getFailingPinCount() const {
        return pin_count;
    }

    void fromFields(const std::vector<std::string>& fields) override;
};

/**
 * @struct PolarlityCheckRecord
 * @brief Record structure for Polarity Check test results (@PCHK)
 * 
 * This record describes the results of Polarity Check tests which verify
 * correct component orientation and polarity on the board.
 * 
 * Generated by: test statement (Polarity Check tests)
 * 
 * Format: {@PCHK|test status|test designator}
 */
struct PolarityCheckRecord : public core::LogRecord {
    enums::GenericTestStatus test_status;      ///< Test execution status
    std::string test_designator;               ///< Test identifier
    
    /**
     * @brief Default constructor
     */
    PolarityCheckRecord() : LogRecord(enums::LogRecordPrefix::PCHK),
                           test_status(enums::GenericTestStatus::PASS) {}
    
    /**
     * @brief Constructor with test designator
     * @param designator Test identifier
     */
    explicit PolarityCheckRecord(const std::string& designator)
        : LogRecord(enums::LogRecordPrefix::PCHK),
          test_status(enums::GenericTestStatus::PASS),
          test_designator(designator) {}
    
    /**
     * @brief Checks if test passed
     * @return true if test status indicates success
     */
    bool isPassed() const {
        return test_status == enums::GenericTestStatus::PASS;
    }
    
    /**
     * @brief Checks if test failed
     * @return true if test status indicates failure
     */
    bool isFailed() const {
        return test_status == enums::GenericTestStatus::FAIL;
    }
    
    /**
     * @brief Checks if fatal error occurred
     * @return true if test encountered fatal error
     */
    bool isFatalError() const {
        return test_status == enums::GenericTestStatus::FATAL_ERROR;
    }

    void fromFields(const std::vector<std::string>& fields) override;
};

/**
 * @struct TestJetRecord
 * @brief Record structure for VTEP or TestJet test results (@TJET)
 * 
 * This record describes the results of VTEP (Vectorless Test Enhanced Probe)
 * or TestJet tests which provide advanced digital testing capabilities
 * without requiring test vectors.
 * 
 * Generated by: test statement (VTEP/TestJet tests)
 * Subrecords: @DPIN (when logging pins to list failing device pins)
 * 
 * Format: {@TJET|test status|pin count|test designator}
 */
struct TestJetRecord : public core::LogRecord {
    enums::GenericTestStatus test_status;      ///< Test execution status
    int pin_count;                             ///< Number of failing pins
    std::string test_designator;               ///< Device or test identifier
    
    /**
     * @brief Default constructor
     */
    TestJetRecord() : LogRecord(enums::LogRecordPrefix::TJET),
                     test_status(enums::GenericTestStatus::PASS),
                     pin_count(0) {}
    
    /**
     * @brief Constructor with test designator
     * @param designator Device or test identifier
     */
    explicit TestJetRecord(const std::string& designator)
        : LogRecord(enums::LogRecordPrefix::TJET),
          test_status(enums::GenericTestStatus::PASS),
          pin_count(0),
          test_designator(designator) {}
    
    /**
     * @brief Checks if test passed
     * @return true if test status indicates success
     */
    bool isPassed() const {
        return test_status == enums::GenericTestStatus::PASS;
    }
    
    /**
     * @brief Checks if test failed
     * @return true if test status indicates failure
     */
    bool isFailed() const {
        return test_status == enums::GenericTestStatus::FAIL;
    }
    
    /**
     * @brief Checks if fatal error occurred
     * @return true if test encountered fatal error
     */
    bool isFatalError() const {
        return test_status == enums::GenericTestStatus::FATAL_ERROR;
    }
    
    /**
     * @brief Gets the number of failing pins
     * @return Pin count (0 if test passed)
     */
    int getFailingPinCount() const {
        return pin_count;
    }

    void fromFields(const std::vector<std::string>& fields) override;
    json toJson() const override;
};

/**
 * @struct IndictmentRecord
 * @brief Record structure for device indictment lists (@INDICT)
 * 
 * This record contains a list of devices indicted by tests as potential
 * failures or known failures. Used with DriveThru technology to identify
 * suspect components. Generated when log level is set to indictments.
 * 
 * Generated by: test statement (with DriveThru)
 * 
 * Format: {@INDICT|technique\device list|est resistance|est capacitance|est inductance|est model}
 */
struct IndictmentRecord : public core::LogRecord {
    std::string technique;                     ///< Analysis technique (e.g., "DT" for DriveThru)
    std::vector<std::string> device_list;      ///< List of indicted device reference designators
    std::optional<double> est_resistance;      ///< Estimated resistance (not used for DriveThru)
    std::optional<double> est_capacitance;     ///< Estimated capacitance (not used for DriveThru)  
    std::optional<double> est_inductance;      ///< Estimated inductance (not used for DriveThru)
    std::string est_model;                     ///< Estimated model (not used for DriveThru)
    
    /**
     * @brief Default constructor
     */
    IndictmentRecord() : LogRecord(enums::LogRecordPrefix::INDICT) {}
    
    /**
     * @brief Constructor with technique
     * @param analysis_technique Analysis method identifier
     */
    explicit IndictmentRecord(const std::string& analysis_technique)
        : LogRecord(enums::LogRecordPrefix::INDICT), technique(analysis_technique) {}
    
    /**
     * @brief Adds a device to the indicted device list
     * @param device_ref Device reference designator
     */
    void addIndictedDevice(const std::string& device_ref) {
        device_list.push_back(device_ref);
    }
    
    /**
     * @brief Gets the number of indicted devices
     * @return Count of devices in the indictment list
     */
    int getIndictedDeviceCount() const {
        return static_cast<int>(device_list.size());
    }
    
    /**
     * @brief Checks if using DriveThru technique
     * @return true if technique is DriveThru
     */
    bool isDriveThru() const {
        return technique == "DT";
    }

    void fromFields(const std::vector<std::string>& fields) override;
    json toJson() const override;
};

/**
 * @struct PinRecord
 * @brief Record structure for pin lists (@PIN)
 * 
 * This record contains a list of pins, typically used in various test contexts.
 * 
 * Generated by: Various test statements
 * 
 * Format: {@PIN\count|pin1|pin2|...}
 * where \count is the number of pins in the list
 */
struct PinRecord : public core::LogRecord {
    std::optional<int> pin_count;              ///< Number of pins in the list
    std::vector<std::string> pins;             ///< List of pin identifiers
    
    /**
     * @brief Default constructor
     */
    PinRecord() : LogRecord(enums::LogRecordPrefix::PIN) {}
    
    /**
     * @brief Gets the number of pins
     * @return Number of pins in the list
     */
    int getPinCount() const {
        return pins.size();
    }
    
    /**
     * @brief Adds a pin to the list
     * @param pin Pin identifier
     */
    void addPin(const std::string& pin) {
        pins.push_back(pin);
    }

    void fromFields(const std::vector<std::string>& fields) override;
    json toJson() const override;
};

} // namespace records
} // namespace keysight_log

#endif // KEYSIGHT_LOG_RECORDS_DIGITALRECORDS_HPP
