/**
 * @file SystemRecords.hpp
 * @brief Defines system-level and batch record structures for Keysight i3070 ICT logs
 * 
 * This header contains all top-level log record structures that manage batch, block,
 * alarm, identification, network verification, node lists, report messages, and retest
 * records as defined by the i3070 Log Record Format.
 * 
 * @author Keysight Log Parser Team
 * @version 1.0
 * @date 2025-06-19
 */

#ifndef KEYSIGHT_LOG_RECORDS_SYSTEMRECORDS_HPP
#define KEYSIGHT_LOG_RECORDS_SYSTEMRECORDS_HPP

#include "../core/LogRecord.hpp"
#include "../enums/LogRecordPrefix.hpp"
#include "../enums/FieldType.hpp"
#include "../utils/JsonKeys.hpp"
#include "../utils/SafeConversion.hpp"
#include <string>
#include <vector>
#include <optional>
#include <nlohmann/json.hpp>
#include <iostream>
#include <cstdint>

using nlohmann::json;
using namespace std;

namespace keysight_log {
namespace records {

/**
 * @struct BatchRecord
 * @brief Log record for identifying a batch of boards (@BATCH)
 * 
 * Generated by: log board statement  
 * Subrecords: BTEST records for each board  
 * Format: {@BATCH|UUT type|UUT rev|fixture id|testhead number|\ 
 *           testhead type|process step|batch id|operator id|controller|\ 
 *           testplan id|testplan rev|parent panel type|parent panel rev}
 */
struct BatchRecord : public core::LogRecord {
    string uut_type;               ///< Unit Under Test type [1]
    string uut_type_rev;           ///< UUT type revision [1]
    int fixture_id;                     ///< Fixture identifier [1]
    int testhead_number;                ///< Testhead number [1]
    string testhead_type;          ///< Testhead type [1]
    string process_step;           ///< Manufacturing process step [1]
    string batch_id;               ///< Batch identifier [1]
    string operator_id;            ///< Operator identifier [1]
    string controller;             ///< Controller name [1]
    string testplan_id;            ///< Testplan identifier [1]
    string testplan_rev;           ///< Testplan revision [1]
    string parent_panel_type;      ///< Parent panel type [1]
    string parent_panel_type_rev;  ///< Parent panel revision [1]
    string version_label;          ///< Version label (optional) [1]

    BatchRecord()
      : LogRecord(enums::LogRecordPrefix::BATCH),
        fixture_id(0),
        testhead_number(1) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct BlockRecord
 * @brief Log record for identifying a test block (@BLOCK)
 * 
 * Generated by: test statements  
 * Subrecords: various test records nested within block  
 * Format: {@BLOCK|block designator|block status}
 */
struct BlockRecord : public core::LogRecord {
    string block_designator; ///< Block name or identifier [1]
    int block_status;             ///< Block pass/fail status [1]

    BlockRecord()
      : LogRecord(enums::LogRecordPrefix::BLOCK),
        block_status(0) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct AlarmRecord
 * @brief Log record for real-time alarms (@ALM)
 * 
 * Generated by: alarm program  
 * Subrecords: AID subrecord identifies board causing alarm  
 * Format: {@ALM|alarm type|alarm status|time detected|board type|\ 
 *           board rev|alarm limit|detected value|controller|testhead number}
 */
struct AlarmRecord : public core::LogRecord {
    int alarm_type;            ///< 1=consecutive failure, 2=sample yield, 3=overall yield [1]
    bool alarm_status;         ///< Alarm on/off flag [1]
    string datetime;      ///< Detection timestamp YYMMDDHHMMSS [1]
    string board_type;    ///< Board type string [1]
    string board_rev;     ///< Board revision string [1]
    optional<int> alarm_limit;           ///< Alarm threshold value [1]
    optional<int> detected_value;        ///< Value that triggered alarm [1]
    string controller;    ///< Controller identifier [1]
    int testhead_number;       ///< Testhead number [1]

    AlarmRecord()
      : LogRecord(enums::LogRecordPrefix::ALM),
        alarm_type(1),
        alarm_status(false),
        testhead_number(1) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct AlarmBoardRecord
 * @brief Subrecord to identify board causing the alarm (@AID)
 * 
 * Generated by: alarm program  
 * Format: {@AID|time detected|serial number}
 */
struct AlarmBoardRecord : public core::LogRecord {
    string datetime;   ///< Alarm occurrence datetime [1]
    string serial;     ///< Board serial number [1]

    AlarmBoardRecord()
      : LogRecord(enums::LogRecordPrefix::AID) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct ArrayRecord
 * @brief Digitizer result summary or analog report record (@ARRAY)
 * 
 * Generated by: digitizer or report analog statement  
 * Format: {@ARRAY|subtest designator|status|failure count|samples}
 */
struct ArrayRecord : public core::LogRecord {
    string designator; ///< Subtest designator string [1]
    int status;             ///< 0=pass, 1=fail, 7=error [1]
    optional<int> failure_count;      ///< Number of failures [1]
    optional<int> samples;            ///< Number of samples [1]

    ArrayRecord()
      : LogRecord(enums::LogRecordPrefix::ARRAY),
        status(0) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct NetVerifyRecord
 * @brief Network verification record (@NETV)
 * 
 * Generated by: prsetup program  
 * Format: {@NETV|datetime|test system|repair system|source}
 */
struct NetVerifyRecord : public core::LogRecord {
    string datetime;    ///< Verification timestamp YYMMDDHHMMSS [1]
    string test_system; ///< Test system identifier [1]
    string repair_system;///< Repair system identifier [1]
    bool source;             ///< 0=prsetup, 1=processed by alarm [1]

    NetVerifyRecord()
      : LogRecord(enums::LogRecordPrefix::NETV),
        source(false) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct NodeListRecord
 * @brief Node list subrecord for probe and boundary tests (@NODE)
 * 
 * Generated by: probe statements  
 * Format: {@NODE\\count|item1|item2|...}
 */
struct NodeListRecord : public core::LogRecord {
    int count;                   ///< Number of nodes in list [1]
    vector<string> nodes; ///< List of node identifiers [1]

    NodeListRecord()
      : LogRecord(enums::LogRecordPrefix::NODE),
        count(0) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct ReportRecord
 * @brief Message log record generated by report statements (@RPT)
 * 
 * Generated by: report statements  
 * Format: {@RPT|message}
 */
struct ReportRecord : public core::LogRecord {
    string message; ///< Report message text [1]

    ReportRecord()
      : LogRecord(enums::LogRecordPrefix::RPT) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct RetestRecord
 * @brief Indicates log clear for retest event (@RETEST)
 * 
 * Generated by: log clear for retest statement  
 * Format: {@RETEST|datetime}
 */
struct RetestRecord : public core::LogRecord {
    string datetime; ///< Retest clear timestamp YYMMDDHHMMSS [1]

    RetestRecord()
      : LogRecord(enums::LogRecordPrefix::RETEST) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct BTestRecord
 * @brief Board test description and results record (@BTEST)
 *
 */
struct BTestRecord : public core::LogRecord {
    string        board_id;      
    int           test_status;         
    uint64_t      start_datetime;           
    int           duration;             
    bool          multiple_test;  
    string        log_level;
    optional<int> log_set;
    bool          learning;
    bool          known_good;
    uint64_t      end_datetime;
    string        status_qualifier;
    int           board_number;
    string        parent_panel_id;

    BTestRecord()
      : LogRecord(enums::LogRecordPrefix::BTEST) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct BoundaryScanRecord
 * @brief Boundary scan test description record (@BS-CON)
 *
 */
struct BoundaryScanRecord : public core::LogRecord {
    string        test_designator;             
    int           status;           
    optional<int> shorts_count;             
    optional<int> opens_count;     

    BoundaryScanRecord()
      : LogRecord(enums::LogRecordPrefix::BS_CON) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct BsOpenRecord
 * @brief Boundary scan open pins list record (@BS-O)
 *
 */
struct BsOpenRecord : public core::LogRecord {
    string first_device_name;
    string first_device_pin;
    string second_device_name;
    string second_device_pin;

    BsOpenRecord()
      : LogRecord(enums::LogRecordPrefix::BS_O) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

/**
 * @struct BsShortRecord
 * @brief Boundary scan short pins list record (@BS-S)
 *
 */
struct BsShortRecord : public core::LogRecord {
    
    string cause;
    optional<int> shorts_count;
    vector<string> node_list;

    BsShortRecord()
      : LogRecord(enums::LogRecordPrefix::BS_S) {}

    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

class PFRecord : public core::LogRecord {
public:
    string designator;
    optional<int> test_status;
    optional<int> total_pins;
    PFRecord() : LogRecord(enums::LogRecordPrefix::PF) {}
    void fromFields(const vector<string>& fields) override;
    nlohmann::json toJson() const override;
};

} // namespace records
} // namespace keysight_log

#endif // KEYSIGHT_LOG_RECORDS_SYSTEMRECORDS_HPP
